---
- name: Install git
  apt:
    name: git
    state: latest
  become: yes
- name: Checkout Nomad module
  git:
    repo: "{{ nomad_module_url }}"
    dest: "/tmp/terraform-aws-nomad"
    version: "{{ nomad_module_version }}"
- name: Install Nomad
  shell: "/tmp/terraform-aws-nomad/modules/install-nomad/install-nomad --version {{ nomad_version }}"
- name: "Copy Nomad Configuration"
  copy:
    src: "{{ role_path }}/files/config/"
    dest: "/opt/nomad/config"
  become: yes
- name: Install Configuration script
  copy:
    src: "{{ role_path }}/files/configure.sh"
    dest: "/opt/nomad/bin/configure"
    mode: 0755
  become: yes
