---
# Amazon Linux AMI follows very closely to CentOS 6
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest
  become: yes
- name: Install git
  yum:
    name: git
    state: latest
  become: yes
- name: Configure dnsmasq
  copy:
    src: "{{ role_path }}/files/10-consul"
    dest: "/etc/dnsmasq.d/10-consul"
  become: yes
# See https://medium.com/zendesk-engineering/making-docker-and-consul-get-along-5fceda1d52b9
- name: Setup Dummy interface
  block:
  # Amazon Linux follows RHEL6 closely
  # https://jamielinux.com/docs/libvirt-networking-handbook/appendix/dummy-interface-on-rhel.html
  - name: Create dummy network interface
    copy:
      src: "{{ role_path }}/files/dummy/dummy.modules"
      dest: "/etc/sysconfig/modules/dummy.modules"
      mode: 0755
    become: yes
  - name: Copy sysconfig/network-scripts files
    copy:
      src: "{{ role_path }}/files/dummy/ifcfg-dummy0"
      dest: "/etc/sysconfig/network-scripts/ifcfg-dummy0"
    become: yes
  - name: Append 127.0.0.1 as nameserver to use dnsmasq on next start-up
    copy:
      src: "{{ role_path }}/files/dummy/dhclient.conf"
      dest: "/etc/dhcp/dhclient.conf"
      mode: 0644
    become: yes
  - name: Enable network service on-startup
    service:
      name: network
      enabled: yes
    become: yes
  - name: Enable dnsmasq service on-startup
    service:
      name: dnsmasq
      enabled: yes
    become: yes
- name: Clone Consul module
  git:
    repo: "{{ consul_module_repo }}"
    dest: "/tmp/terraform-aws-consul"
    version: "{{ consul_module_version }}"
- name: Install Consul
  shell: "/tmp/terraform-aws-consul/modules/install-consul/install-consul --version {{ consul_version }}"
- name: Copy Consul Configuration
  copy:
    src: "{{ role_path }}/files/config/"
    dest: "/opt/consul/config"
  become: yes
