services:
  - docker

install:
  - docker build -t lint -f Dockerfile-lint .

script:
  - docker run --rm -ti lint modules/core
  - docker run --rm -ti lint modules/nomad-vault-integration

branches:
  only:
  - master

notifications:
  email: false
