services:
  - docker

install:
  - docker build -t lint -f Dockerfile-lint .

script:
  - docker run --rm -ti --entrypoint terraform lint fmt -check=true
  - find modules/ -mindepth 1 -maxdepth 1 -type d -exec docker run --rm -ti lint {} \;

branches:
  only:
  - master

notifications:
  email: false
