---
  nomad_version: "0.8.3"
  nomad_module_url: "https://github.com/hashicorp/terraform-aws-nomad.git"
  nomad_module_version: "v0.1.1"
  docker_version: "18.04.0~ce~3-0~ubuntu"
  nomad_user: "nomad"
  consul_template_user: "root"
