---
- name: Get Ubuntu release name
  shell: lsb_release -cs
  register: release_name
- name: Get the install script
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-ubuntu-{{ release_name.stdout }}-td-agent3.sh"
    dest: "{{ td_agent_tmp_file }}"
    mode: 0400
- name: Run the install script
  command: "sh {{ td_agent_tmp_file }}"
  become: yes
- name: Copy td-agent configuration into host
  copy:
    src: "{{ role_path }}/files/td-agent.conf"
    dest: "/etc/td-agent/td-agent.conf"
    mode: 0644
  become: yes
- name: Enable and restart the td-agent service
  service:
    name: td-agent
    state: restarted
    enabled: yes
  become: yes
- name: Install fluent-plugin-systemd
  command: "td-agent-gem install fluent-plugin-systemd -v {{ fluent_plugin_systemd_version }}"
  become: yes
- name: Remove install script
  file:
    path: "{{ td_agent_tmp_file }}"
    state: absent
