---
- name: Get Ubuntu release name
  shell: lsb_release -cs
  register: release_name
- name: Get the install script
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-ubuntu-{{ release_name.stdout }}-td-agent3.sh"
    dest: "{{ td_agent_tmp_file }}"
    mode: 0400
- name: Run the install script
  command: "sh {{ td_agent_tmp_file }}"
  become: yes
- name: Disable and stop the td-agent service
  service:
    name: td-agent
    state: stopped
    enabled: no
  become: yes
- name: Install fluent-plugin-systemd
  command: "td-agent-gem install fluent-plugin-systemd -v {{ fluent_plugin_systemd_version }}"
  become: yes
- name: Remove install script
  file:
    path: "{{ td_agent_tmp_file }}"
    state: absent
