---
- name: Provision AMI
  hosts: all
  vars:
    nomad_version: "0.8.2"
    nomad_module_version: "v0.1.1"
    consul_module_version: "v0.1.0"
    consul_version: "1.0.1"
    vault_version: "0.10.1"
    vault_module_version: "v0.4.0"
    ca_certificate: ""
  pre_tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../roles/consul"
  - name: Install Vault
    include_role:
      name: "{{ playbook_dir }}/../roles/install-vault"
  - name: Install Nomad
    include_role:
      name: "{{ playbook_dir }}/../roles/nomad"
  - name: Install CA Certificate
    include_role:
      name: "{{ playbook_dir }}/../roles/ansible-ca-store"
    vars:
      certificate: "{{ ca_certificate }}"
      certificate_rename: "ca.crt"
    become: yes
    when: ca_certificate
  - name: Install Vault SSH Configuration Script
    include_role:
      name: "{{ playbook_dir }}/../roles/install-ssh-script"
