---
- name: Provision AMI
  hosts: all
  vars:
    nomad_version: "0.8.5"
    nomad_module_version: "v0.1.1"
    consul_module_version: "v0.3.5"
    consul_version: "1.2.3"
    vault_version: "0.11.1"
    vault_module_version: "v0.4.1"
    consul_enable_syslog: true
    nomad_enable_syslog: true
    td_agent_config_file: ""
    td_agent_config_vars_file: ""
    td_agent_config_dest_file: "/etc/td-agent/td-agent.conf"
    ca_certificate: ""
    consul_host: ""
    consul_port: 443
    consul_scheme: https
    consul_token: ""
    consul_integration_prefix: "terraform/"
    nomad_additional_config: []
  pre_tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install CA Certificate
    include_tasks: "{{ playbook_dir }}/../../../../tasks/include_role_checked.yml"
    vars:
      role: "{{ playbook_dir }}/../../../../roles/ansible-ca-store"
      certificate: "{{ ca_certificate }}"
      certificate_rename: "ca.crt"
    become: yes
    when: ca_certificate != ""
  - name: Install Vault PKI CA Certificate
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/vault-pki"
  - name: Install td-agent
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/td-agent"
    vars:
      config_file: "{{ td_agent_config_file }}"
      config_vars_file: "{{ td_agent_config_vars_file }}"
      config_dest_file: "{{ td_agent_config_dest_file }}"
  - name: Install Telegraf
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/telegraf"
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/consul"
    vars:
      consul_client_address: "127.0.0.1 169.254.1.1"
  - name: Install Vault
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-vault"
  - name: Install Nomad
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/nomad"
  - name: Install Vault SSH Configuration Script
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-ssh-script"
