---
- name: Install dependencies
  apt:
    name:
      - "libssl-dev"
      - "software-properties-common"
    state: latest
  become: yes
- name: Install Ansible via Pip
  pip:
    name: ansible
    version: "{{ ansible_install_version }}"
    state: present
  become: yes