---
- name: Provision Consul AMI
  hosts: all
  vars:
    consul_module_repo: "https://github.com/hashicorp/terraform-aws-consul.git"
    consul_module_version: "v0.1.0"
    consul_version: "1.1.0"
    consul_enable_syslog: true
    td_agent_config_file: ""
    td_agent_config_vars_file: ""
    td_agent_config_dest_file: "/etc/td-agent/td-agent.conf"
    telegraf_config_file: ""
    telegraf_config_vars_file: ""
    telegraf_config_dest_file: "/etc/telegraf/telegraf.conf"
    ca_certificate: ""
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install td-agent
    include_role:
      name: "{{ playbook_dir }}/../roles/td-agent"
    vars:
      config_file: "{{ td_agent_config_file }}"
      config_vars_file: "{{ td_agent_config_vars_file }}"
      config_dest_file: "{{ td_agent_config_dest_file }}"
  - name: Install Telegraf
    include_role:
      name: "{{ playbook_dir }}/../roles/telegraf"
    vars:
      config_file: "{{ telegraf_config_file }}"
      config_vars_file: "{{ telegraf_config_vars_file }}"
      config_dest_file: "{{ telegraf_config_dest_file }}"
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../roles/consul"
  - name: Install Consul-Template
    include_role:
      name: "{{ playbook_dir }}/../roles/install-consul-template"
  - name: Install CA Certificate
    include_role:
      name: "{{ playbook_dir }}/../roles/ansible-ca-store"
    vars:
      certificate: "{{ ca_certificate }}"
      certificate_rename: "ca.crt"
    become: yes
    when: ca_certificate
  - name: Install Vault SSH Configuration Script
    include_role:
      name: "{{ playbook_dir }}/../roles/install-ssh-script"
