---
- name: Provision Consul AMI
  hosts: all
  vars:
    consul_module_version: "v0.1.0"
    consul_version: "1.0.1"
    ca_certificate: ""
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../roles/consul"
  - name: Install CA Certificate
    include_role:
      name: "{{ playbook_dir }}/../roles/ansible-ca-store"
    vars:
      certificate: "{{ ca_certificate }}"
      certificate_rename: "ca.crt"
    become: yes
    when: ca_certificate
