---
- name: Provision AMI
  hosts: all
  vars:
    vault_version: "0.10.0"
    vault_ui_enable: "true"
    vault_module_version: "v0.4.0"
    consul_module_version: "v0.1.2"
    consul_version: "1.0.6"
    consul_key: "vault/"
    tls_cert_file_src: "{{ playbook_dir }}/cert/cert.pem"
    encrypted_tls_key_file_src: "{{ playbook_dir }}/cert/encrypted_vault.key"
    encrypted_aes_key_src: "{{ playbook_dir }}/cert/aes.key"
    cli_json_src: "{{ playbook_dir }}/cert/cli.json"
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../roles/consul"
  - name: Install Vault
    include_role:
      name: "{{ playbook_dir }}/../roles/vault"
