---
- name: Provision AMI
  hosts: all
  vars:
    vault_version: "0.9.6"
    vault_module_version: "v0.4.0"
    consul_module_version: "v0.1.2"
    consul_version: "1.0.6"
    consul_key: "vault"
    tls_cert_file: "{{ playbook_dir }}/vault.crt"
    tls_key_file: "{{ playbook_dir }}/vault.key"
  pre_tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  roles:
  - role: "{{ playbook_dir }}/../roles/consul"
  - role: "{{ playbook_dir }}/../roles/vault"
